name: Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install pnpm
      run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm

    - name: Set up Node.js (if using Node.js for build)
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # or your preferred version

    - name: Install dependencies and build (if necessary)
      run: |
        pnpm install
        pnpm run build

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Upload artifacts to GCS
      run: |
        gsutil -m cp -r ./dist/* gs://${{ secrets.GCS_BUCKET_NAME }}/${GITHUB_REPOSITORY}/${GITHUB_SHA}

    - name: Update import map
      run: |
        curl -u ${{ secrets.DEPLOYER_USERNAME }}:${{ secrets.DEPLOYER_PASSWORD }} \
        -d '{ "service":"@ssm/'"${GITHUB_REPOSITORY}"'", "url":"https://storage.googleapis.com/'"${GITHUB_REPOSITORY}"'/'"${GITHUB_SHA}"'/ssm-'"${GITHUB_REPOSITORY}"'.js" }' \
        -X PATCH https://${{secrets.DEPLOYER_HOST}}/services\?env=test \
        -H "Accept:application/json" -H "Content-Type:application/json" --fail --insecure -i
